[package]

name = "sparkle"
version = "0.0.1"
authors = ["Liaud <rph.vaillant@gmail.com>"]

[lib]

name = "sparkle"
path = "src/lib.rs"

[dependencies.split_access]

git = "https://github.com/Bastacyclop/split_access.git"
