env:
  global:
    - secure: Xynl6Z81cbzmL24un1yckLrNifxRpQXX8MSfZXGCP7/4X7esi5x8HKxt9WcVYVSjOtqaDskxMu9V8b6yrr1EbM+MmH0HRyJ8nGGAo7BW9/tDrh63lmbZSR7Vlf+USCS2svzESVhLbEtNeAxmzEKJVRdQbSfjXBZWWOGEl86AFzk=
language: rust
script:
  - cd sparkle
  - cargo build --verbose
  - cargo doc --no-deps --verbose
  - mv target/doc ../doc
after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
