env:
  global:
    - secure: YhUaNx7vZooCHruUajsxayBPMSy0nXm0rvU9PbOQu6xXo/ctHZdXYUZTOloKfGMEmfLfVBWG3NlSVHUNW1xitFRrRpFY6w54XGaH0KhwtoO2yARERIqZ/rtrkLy7/u0ReP9N7S01/XiPnGXyNtOOZwe8XCQ94nhasUn3uE1OfWw=
language: rust
script:
  - cd sparkle
  - cargo build --verbose
  - cargo doc --no-deps --verbose
after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
